### ISSUE TITLE
HA 2024.01 breaking changes

### ISSUE THREAD

**Issue by leonardpitzu** [epoplavskis/homeassistant_salus#54]
HA Core 2024.01 brings some changes which make this integration incompatible

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable`

**Comment by Dozzki** [comment]
@epoplavskis having same issue here. Is this even maintained still?

**Comment by ChristophCaina** [comment]
might be related blog post from HA:
https://developers.home-assistant.io/docs/core/entity/climate#supported-features

I've had a look into the source of the climate.py

```
from homeassistant.components.climate.const import (
    HVAC_MODE_HEAT,
    HVAC_MODE_COOL,
    HVAC_MODE_OFF,
    FAN_OFF,
    FAN_AUTO,
    FAN_LOW,
    FAN_MEDIUM,
    FAN_HIGH
)
```

I am unsure, if this is related to the `FAN_***` modes - usually, it would be:
FAN_MODE.OFF, FAN_MODE.MEDIUM etc.
which is now depricated... 

ClimateEntityFeature.


The above would also explain this case:
#46 which is open since June... I wonder if this integration is still "alive" and maintained...

**Comment by Dozzki** [comment]
It is actually fixed by HA team in new beta release 2024.1.0b5. With last release they changed some things and didnt leave backwards compatibility. With this one they added backwards compatibility to climate entity and it started working again. 
Now, regarding maintenance of this project, i believe it was handed over to different person like 3 months ago as original author mentioned he was not maintaining it anymore. But the new maintainer don't have any git history for the past 3 years so iam not sure why it was handed over to person who is not active in the community 🤷 sad

**Comment by mjrybarski** [comment]
any news I just got the integration and fan still says 'Failed to perform the action climate/set_hvac_mode. Unknown error occurred while communicating with iT600 gateway'

**Comment by leonardpitzu** [comment]
I have no device with a fan so I cannot debug it...
